### ISSUE TITLE
can't use annotation field as table field

### ISSUE THREAD

**Issue by lelvisl** [camptocamp/grafana-prometheus-alertmanager-datasource#12]
Alertmanager always gives 1 as value for all active alarms.

for example
```yaml
alert: high_load
expr: (1
  - (avg(irate(node_cpu{job="node",mode="idle"}[5m])) WITHOUT (cpu)))
  > 0.6
for: 1m
labels:
  severity: warning
annotations:
  description: Instance {{ $labels.instance }} cpu over 60%
  resolved: Instance {{ $labels.instance }} cpu is ok
  summary: Instance {{ $labels.instance }} cpu over 60%
  value: '{{$value}}'
``` 
I can add value to description, bun can't set value to separated field in grafana table.
