### ISSUE TITLE
error: json: unsupported type: map[interface {}]interface {}

### ISSUE THREAD

**Issue by wollf01** [camptocamp/grafana-prometheus-alertmanager-datasource#26]
apiVersion: 1
    datasources:
    - name: AlertManager
      type: camptocamp-prometheus-alertmanager-datasource
      access: proxy
      url: http://alertmanager:9093/alertmanager
      orgId: 1
      version: 1
      editable: true
      jsonData:
        severity:
          critical: 3
          warning: 2
          info: 1

I have json configuration for alertmanger plugin, but while start grafana, i get below errors:

> t=2018-05-10T00:06:10+0000 lvl=eror msg="Startup failed" error="Failed to provision Grafana from config. error: json: unsupported type: map[interface {}]interface {}"
t=2018-05-10T00:06:10+0000 lvl=info msg="Shutdown started" logger=server code=1 reason="startup error"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xef1f56]

goroutine 21 [running]:
github.com/grafana/grafana/pkg/api.(*HttpServer).Shutdown(0x0, 0x1f87fe0, 0xc42023bc80, 0xc42023b400, 0x4)
        /go/src/github.com/grafana/grafana/pkg/api/http_server.go:97 +0x26
main.(*GrafanaServerImpl).Shutdown(0xc42023bd00, 0x1, 0x144d9cf, 0xd)
        /go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/server.go:137 +0x19f
main.listenToSystemSignals(0xc42023bd00, 0xc420126660)
        /go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/main.go:118 +0x291
created by main.main
        /go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/main.go:85 +0x2a3

I tried to remove jsonData section, then grafana can be started correctly, but severity information is not there, may i know how to process jsonData section ?

**Comment by SPFZ** [comment]
Hi,
you are hitting this bug that I opened in the grafana repo grafana/grafana/issues/11537
Feel free to comment/thumbup there that you have the same issue.
Greetings,
SPFZ

**Comment by njbartlett** [comment]
I wonder if it would be easier to patch the plugin to avoid using nested values in its config, rather than waiting for Grafana to fix their bug? This would make the plugin compatible with a wider range of Grafana versions.

**Comment by cryptobioz** [comment]
I can't reproduce but I made a PR that should fix this error: #30. Could you test it?

**Comment by njbartlett** [comment]
Yes the PR works. I created a provisioning file, `/etc/grafana/provisioning/datasources/alertmanager.yaml` as follows:

``` yaml
apiVersion: 1

datasources:
- name: ASOPS Alert Manager
  type: camptocamp-prometheus-alertmanager-datasource
  access: proxy
  url: http://.../
  isDefault: false
  jsonData:
    timeInterval: 15s
    severity_critical: "4"
    severity_high: "3"
    severity_warning: "2"
    severity_info: "1"
  version: 1
  editable: true
```

These files were loaded into the plugin, and the datasource worked immediately without further manual configuration. 👍
