### ISSUE TITLE
Severity field is "blank" even though response has severity = "critical"

### ISSUE THREAD

**Issue by prashantsr** [camptocamp/grafana-prometheus-alertmanager-datasource#31]
I've a panel with type table but severity column is blank. Is there a configuration on the datasource for severity?

**Comment by rk126** [comment]
I am also seeing this issue, the prometheus alertmanager query response has the severity label key value pair present, but somehow the front end is getting messed up.

**Comment by cryptobioz** [comment]
Are you using the latest version of the plugin? Did you define severity levels on the datasource configuration page (cf. #13)?

**Comment by VR6Pete** [comment]
@cryptobioz the logic is flawed, what about for those with custom severity levels? 
I think it needs more flexibility for where this can be configured.

**Comment by rk126** [comment]
@cryptobioz I did define the severity levels but realized that the latest release 0.0.5 doesn't have the fix #26 
There's a bug opened in Grafana as it is not able to use nested JSON data mentioned in our severity levels' datasource configuration.
With that keeping in mind, I tried out installing the master and still facing the difficulty as I am seeing an empty Severity column.

**Comment by rk126** [comment]
I used the following configuration when I installed f6ccded (master top) version of this plugin.

{
        "name": "AlertManager",
        "type": "camptocamp-prometheus-alertmanager-datasource",
        "url":"http://...",
        "access": "proxy",
        "jsonData": {
            "severity_critical": "4",
            "severity_high": "3",
            "severity_info": "1",
            "severity_warning": "2"
        }
    }

**Comment by robshelly** [comment]
Also seeing this issue. 
Provisioned the data source during installation using the followuing config:

```
    apiVersion: 1
    datasources:
    - name: AlertManager
      type: camptocamp-prometheus-alertmanager-datasource
      url: https://alertmanager.127.0.0.1.nip.io
      access: direct
      jsonData:
        timeInterval: 10s
        severity_critical: "4"
        severity_high: "3"
        severity_warning: "2"
        severity_info: "1"
```
Confirmed on the UI that the severity levels have been configured correctly.
Using the latest version of Grafana with the nested json issue [#26](https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/issues/26) and [merged](https://github.com/grafana/grafana-plugin-repository/pull/286) to grafana-plugin-repository but still seeing blank severity fields in Grafana
