### ISSUE TITLE
Adding Datasource fails with TypeError

### ISSUE THREAD

**Issue by prologic** [camptocamp/grafana-prometheus-alertmanager-datasource#44]
Getting this error when "Save and Test""

```
TypeError: Cannot read property 'toLowerCase' of undefined
```

Have I misconfigured or is this a KP?

**Comment by mohsen0** [comment]
the workaround is to set the severity levels in datastore section to a value.
![screenshot 2018-10-23 at 18 12 33](https://user-images.githubusercontent.com/135178/47378196-510af300-d6ef-11e8-967e-b12734d5735b.png)

**Comment by prologic** [comment]
Ahh I see. I'll try that, Thanks!

**Comment by justin-watkinson-sp** [comment]
Found this while setting up provisioned datasources.  Make sure you include this block to populate the severity labels.  I had them as integers and ran into this same error message:

```
  # Alertmanager Attributes
  jsonData:
    severity_critical: "4"
    severity_high: "3"
    severity_warning: "2"
    severity_info: "1"
```
