### ISSUE TITLE
 AlertManager plugin failed TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by scriptdb** [camptocamp/grafana-prometheus-alertmanager-datasource#50]
I have configured Alertmanager data source in K8s ConfigMap:

```
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: AlertManager
      type: camptocamp-prometheus-alertmanager-datasource
      url: http://{{ template "prometheus-operator.fullname" . }}-alertmanager:9093/{{ trimPrefix "/" .Values.prometheus.prometheusSpec.routePrefix }}
      access: proxy     
```

It does load fine and I see the data source in the Grafana UI. 
When I go to the dashboard nothing loads and get the following error:
>  AlertManager plugin failed TypeError: Cannot read property 'toLowerCase' of undefined

If I configure the data source manually via the Kibana UI and make the dashboard point to it everything loads fine and I'm able to see all stats in the dashboard.

What am I missing the in the ConfigMap to make it work?
