### ISSUE TITLE
severity field empty

### ISSUE THREAD

**Issue by AIXruth** [camptocamp/grafana-prometheus-alertmanager-datasource#70]
In my dashboard the table column "severity" is always empty, no matter which value I use. Even if I didn't label "severity", the table would show an empty column.

My sample alerts.yml file:
```
- alert: probe_success
        expr: probe_success == 0
        for: 1m
        labels:
          prio: 2
          severity1: warning
          sev: 1
          Severity: 1
        annotations:
          summary: "S: {{ $labels.instance }} probe failed"
          description: "D: {{ $labels.instance }} probe failed"
```
prio, severity1, sev, and Severity (capital S) work as expected, but an label entry like
```
         labels:    
            severity: 2
```
```
         labels:    
            severity: warning
```

won't fill the always empty shown column "severity".

Bug or wrong usage/configuration?

Environment: Debian10, grafana-6.5.2, alertmanager 0.20.0, prometheus 2.7.1
