### ISSUE TITLE
Grafana 6.4 Could not find plugin definition for data source: camptocamp-prometheus-alertmanager-datasource

### ISSUE THREAD

**Issue by dudubis** [camptocamp/grafana-prometheus-alertmanager-datasource#74]
Hi,

I have the following configuration working with Grafana 5.3, but failing in Grafana 6.4.2 (installed with prometheus operator):

```
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: AlertManager
      type: camptocamp-prometheus-alertmanager-datasource
      url: http://{{ template "prometheus-operator.fullname" . }}-alertmanager:9093/{{ trimPrefix "/" .Values.prometheus.prometheusSpec.routePrefix }}
      access: proxy
      jsonData:
        keepCookies: "[]"
        severity_critical: "4"
        severity_high: "3"
        severity_warning: "2"
        severity_info: "1"
```
In the log I get:
`2020-04-01T13:41:58+0000 lvl=eror msg="Could not find plugin definition for data source: camptocamp-prometheus-alertmanager-datasource"`

Other data source like elasticsearch are installed as expected.
